# Generated by Django 5.0.2 on 2024-06-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picproject', '0004_category_customer_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
