# Generated by Django 5.0.2 on 2024-08-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picproject', '0007_profile_old_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField(max_length=15000)),
            ],
        ),
    ]
