# Generated by Django 5.0.2 on 2024-09-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picproject', '0008_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'contactus'},
        ),
    ]
