import time

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By

serv_obj=Service('D:\Drivers\chromedriver_win32\chromedriver.exe')

driver = webdriver.Chrome(service=serv_obj)
driver.get('https://testautomationpractice.blogspot.com/')
driver.maximize_window()
time.sleep(5)

#window_id=driver.current_window_handle
#print(window_id) #27E7ACEC599FFA63F6F1A7F88275B9AA
                 #7AB7BAAD01A503B83665F03093E05149
driver.find_element(By.XPATH,"//button[@onclick='myFunction()']").click()
time.sleep(5)
window_ids=driver.window_handles # it comes in form of list

# Approach first 1

# v1=window_ids[0]
# v2=window_ids[1]
# print(v1, " and " ,v2)
# driver.switch_to.window(v2)
# time.sleep(3)
# print("Title of child ",driver.title)
# driver.switch_to.window(v1)
# time.sleep(3)
# print("Title of parent ",driver.title)

# Approach 2

# for i in window_ids:
#     #print(i)
#     driver.switch_to.window(i)
#     print(driver.title)
time.sleep(3)
for i in window_ids:
    #print(i)
    driver.switch_to.window(i)
    if driver.title=='Automation Testing Practice':
        driver.close()
time.sleep(3)
driver.close()


# By default driver focuses on parent window
#driver.switch_to.window(windowID)  when browser window is open , automatically/Dynamically window id is generated
# those id is generated by browser itself

#driver.current_window_handle -- return windowID of single browser window
#driver.window_handles -- returns window id's of multiple browser windows